### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by bodorjzsolt** [smstuebe/stackoverflow-answers#2]
Actually it's about the licensing of content from the blog, because in my case the initial post is there(https://smstuebe.de/2016/08/29/underlinedlabel.xamarin.forms/) . For compliance's sake, could you tell me what license applies to the code from the blog? 
"Feel free to use these if you want to play around or have a closer look to effects." could seem a little vague.

**Comment by smstuebe** [comment]
@bodorjzsolt Just use it if you want ^^ If you need to tell your boss a license then: MIT. The blog post was written to share knowledge. And what value does this knowledge have, if you can't use it?! And I think meanwhile it's built-in in Xamarin Forms and there is already a successor for Forms.

**Comment by bodorjzsolt** [comment]
Thank you!
